"""Renombrar is_activate a is_active

Revision ID: 572185956d69
Revises: 089fc7c96322
Create Date: 2025-07-09 12:21:55.581310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572185956d69'
down_revision: Union[str, Sequence[str], None] = '089fc7c96322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users','is_activate',new_column_name="is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activate', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
